"""add_email_to_otps

Revision ID: 083ed63f9dd2
Revises: 36d9c78bb15e
Create Date: 2026-04-02 21:07:59.107546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '083ed63f9dd2'
down_revision: Union[str, Sequence[str], None] = '36d9c78bb15e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_otps', sa.Column('email', sa.String(length=255), nullable=True))
    op.alter_column('email_otps', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_email_otps_email'), 'email_otps', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_otps_email'), table_name='email_otps')
    op.alter_column('email_otps', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('email_otps', 'email')
    # ### end Alembic commands ###
